"""Build a complete static KWS catalog from audited local source content."""
from pathlib import Path
from bs4 import BeautifulSoup
from urllib.parse import urljoin, urlparse, quote
from html import escape as esc
import json, csv, os, re, hashlib
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'website';CONTENT=ROOT/'content';SOURCE='https://www.scentairmachines.com';SITE_URL=os.environ.get('SITE_URL','').rstrip('/')
if SITE_URL and urlparse(SITE_URL).scheme not in ['http','https']:raise ValueError('SITE_URL must be an absolute http(s) origin')
E=lambda x:esc(str(x),quote=True)
visuals=json.loads((CONTENT/'visual-assets.json').read_text())
editorial=json.loads((CONTENT/'editorial.json').read_text())
products=json.loads((CONTENT/'products.json').read_text());media=json.loads((CONTENT/'media.json').read_text());resources=json.loads((CONTENT/'resources.json').read_text())
category_names=[('Scent Air Machines','Space scent machines','Fragrance'),('HVAC Scent Diffuser Machine','HVAC scent diffusers','Fragrance'),('Aroma Scent Machine','Aroma diffusers','Fragrance'),('Car Scent Diffuser','Car diffusers','Fragrance'),('Aerosol Air Freshener Dispenser','Aerosol dispensers','Fragrance'),('Aroma Diffuser Essential Oil','Essential oils','Fragrance'),('Fragrance Gift Sets','Fragrance gift sets','Fragrance'),('Automatic Touchless Soap Dispenser','Touchless soap dispensers','Hygiene'),('Manual Soap Dispenser','Manual soap dispensers','Hygiene'),('Hand Paper Towel Dispenser','Paper dispensers','Hygiene'),('Lightweight Hair Dryer','Hair dryers','Hygiene'),('Wall Mounted Hand Dryer','Hand dryers','Hygiene'),('Pedal Sanitary Bin','Pedal bins','Hygiene'),('Automatic Sanitary Bin','Automatic sanitary bins','Hygiene')]
slug=lambda s:re.sub(r'[^a-z0-9]+','-',s.lower()).strip('-')
categories=[{'source':a,'name':b,'group':c,'slug':slug(a)} for a,b,c in category_names];category_map={c['source']:c for c in categories}
for p in products:
    p['path']=f'/products/p-{p["id"]}/';p['category']=p.get('category') if p.get('category') in category_map else next((c for c in p['categories'] if c in category_map),'Scent Air Machines')
lookup={p['id']:p for p in products};routes=[];redirects=[];corrections=[]
arrow='<span class="arrow" aria-hidden="true">↗</span>'
def image(m,alt,thumb=False,cls='',eager=False):
    if not m:return '<div class="image-fallback" role="img" aria-label="Product image unavailable">KWS<br><small>Contact us for product images</small></div>'
    src=m.get('thumb') if thumb else m.get('src');src=src or m['src']
    return f'<img src="{E(src)}" alt="{E(alt)}" width="{m.get("width",800)}" height="{m.get("height",800)}" class="{E(cls)}" {"fetchpriority=high" if eager else "loading=lazy"} decoding="async">'
def asset(v):return media.get(urljoin(SOURCE+'/',v))
logo=visuals['brand-transparent']
def brand():return f'<a class="brand" href="/" aria-label="KWS Hygiene home">{image(logo,"",eager=True)}<span class="brand-type"><strong>KWS</strong><span>HYGIENE & FRAGRANCE</span></span></a>'
navitems=[('Products','/products/','products'),('Applications','/applications/','applications'),('Manufacturing','/manufacturing/','manufacturing'),('About KWS','/about/','about'),('Resources','/resources/','resources')]
def header(active):
    links=''.join(f'<a href="{path}" {"aria-current=page" if active==key else ""}>{name}</a>' for name,path,key in navitems)
    return f'''<a href="#main" class="skip">Skip to content</a><header class="site-header"><div class="header-inner wrap">{brand()}<button class="menu-toggle" type="button" aria-expanded="false" aria-controls="site-nav" aria-label="Open navigation"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M3 7h18M3 12h18M3 17h18"/></svg></button><nav class="site-nav" id="site-nav" aria-label="Main navigation">{links}<a href="/contact/" class="btn">Let's talk {arrow}</a></nav></div><div class="scroll-line" aria-hidden="true"></div></header>'''
def footer():
    return f'''<footer class="footer"><div class="wrap"><div class="footer-grid"><div>{brand()}<p>Fragrance and hygiene equipment<br>for everyday spaces.</p></div><div><h3>Explore</h3><ul><li><a href="/products/">All products</a></li><li><a href="/applications/">Applications</a></li><li><a href="/manufacturing/">Our factory</a></li><li><a href="/quality/">Quality & documents</a></li></ul></div><div><h3>Company</h3><ul><li><a href="/about/">About KWS</a></li><li><a href="/resources/">Product videos</a></li><li><a href="/news/">News</a></li><li><a href="/contact/">Contact</a></li></ul></div><div><h3>Get in touch</h3><ul><li><a href="mailto:mandyxu@scentairmachines.com">mandyxu@scentairmachines.com</a></li><li><a href="tel:+8613590491364">+86 135 9049 1364</a></li><li><a href="https://wa.me/8613590491364" target="_blank" rel="noopener">WhatsApp {arrow}</a></li></ul><p>Building B, No. 106 Lingnan Road,<br>Tangxia, Dongguan, Guangdong, China</p></div></div><div class="footer-end"><span>© 2026 Dongguan KWS Hygiene Industrial Co., Ltd.</span><span><a href="/privacy/">Privacy</a> &nbsp; / &nbsp; <a href="/site-map/">Site map</a></span><button class="to-top" data-top type="button" aria-label="Back to top">↑</button></div></div></footer>'''
def zoom_dialog():return '<dialog id="image-zoom" aria-label="Expanded image"><div class="zoom-close"><button type="button" id="close-zoom">Close ×</button></div><img id="zoom-image" alt=""></dialog>'
def page(path,title,description,body,active='',schema=None,zoom=False):
    canonical=f'<link rel="canonical" href="{E(SITE_URL+path)}">' if SITE_URL else ''
    data=json.dumps(schema,ensure_ascii=False).replace('<','\\u003c') if schema else ''
    structured=f'<script type="application/ld+json">{data}</script>' if schema else ''
    html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{E(title)} | KWS Hygiene</title><meta name="description" content="{E(description[:250])}"><meta name="robots" content="{"index,follow" if SITE_URL else "noindex,nofollow"}"><meta name="theme-color" content="#173e32"><meta property="og:title" content="{E(title)} | KWS Hygiene"><meta property="og:description" content="{E(description[:250])}"><meta property="og:type" content="website">{canonical}<link rel="icon" href="{E(logo['src'])}" type="image/webp"><link rel="stylesheet" href="/assets/site.css"><script defer src="/assets/site.js"></script>{structured}</head><body>{header(active)}<main id="main">{body}</main>{footer()}{zoom_dialog() if zoom else ''}</body></html>'''
    target=OUT/(path.lstrip('/')+'index.html') if path.endswith('/') else OUT/path.lstrip('/')
    target.parent.mkdir(parents=True,exist_ok=True);target.write_text(html);routes.append(path)
def intro(label,title,desc,crumb=''):
    return f'<div class="wrap page-intro">{f"<nav class=breadcrumb aria-label=Breadcrumb><a href=/>Home</a><span>/</span><span>{E(crumb)}</span></nav>" if crumb else ""}<p class="eyebrow">{E(label)}</p><h1>{title}</h1><p class="lead muted">{desc}</p></div>'
def cta():return f'<section class="inquiry-band"><div class="wrap two-col"><div><p class="eyebrow">Start a conversation</p><h2>A better fit for<br>your space.</h2></div><div><p>Tell us about your project, product requirements or distribution plans. Our team will help you explore the options.</p><div class="btn-row"><a class="btn" href="/contact/">Talk to KWS {arrow}</a><a class="text-link" href="https://wa.me/8613590491364" target="_blank" rel="noopener">WhatsApp {arrow}</a></div></div></div></section>'
def card(p,catalog=False):
    attrs=f'data-product data-search="{E((p["title"]+" "+p.get("model","")+" "+p["category"]).lower())}" data-title="{E(p["title"])}" data-model="{E(p.get("model",""))}"' if catalog else ''
    category=category_map[p['category']]['name']
    return f'<a class="product-card" href="{p["path"]}" {attrs}><div class="product-image">{image(p.get("image"),p["title"],thumb=True)}</div><p class="model">{E(p.get("model") or "KWS "+p["id"])}</p><h3>{E(p["title"])}</h3><div class="card-bottom"><span>{E(category)}</span>{arrow}</div></a>'
def pick(pid,category=None):
    return lookup.get(str(pid)) or next((p for p in products if p['category']==category and p.get('image')),products[0])
featured=[pick('31772096'),pick('13834816'),pick('13512964'),pick('26472271')]
hero=pick('13834816');hygiene=pick('13512964');factory=asset('/photo/scentairmachines/editor/20210221144154_33215.jpg')
apps=[('01','Hotels & hospitality','Explore scent diffusion for reception areas, guest rooms and shared spaces.','HVAC Scent Diffuser Machine'),('02','Retail & workplaces','Fragrance options for shops, offices and customer-facing environments.','Scent Air Machines'),('03','Hygiene & washrooms','Soap, paper and hand-drying equipment for shared facilities.','Automatic Touchless Soap Dispenser')]
def app_blocks():return ''.join(f'<article class="application"><span class="index">{num}</span><h3>{name}</h3><p>{desc}</p><a class="text-link" href="/categories/{category_map[cat]["slug"]}/">Explore products {arrow}</a></article>' for num,name,desc,cat in apps)
def spatial_showroom():
    scenes=[('hotel','01','Hotel lobby','A welcoming first impression.','planning','13834816',[(48,58,'Scent diffusion','A starting point for a lobby fragrance discussion. Confirm placement, airflow and the selected model with KWS.','13834816'),(78,60,'Fragrance refills','Select a compatible fragrance refill for the exact equipment and desired atmosphere.','13490105')]),('office','02','Workplace','Care for the spaces you share.','office-scene','31772096',[(73,54,'Reception scent','Review a standalone diffuser for reception. Placement and operating settings depend on the real layout.','31772096'),(30,58,'Shared-space fragrance','Discuss fragrance choice and maintenance access before selecting a refill.','13490105')]),('washroom','03','Shared washroom','Everyday care, considered.','washroom-scene','13512964',[(68,38,'Touchless soap','Check soap compatibility, mounting, power and replenishment for the selected dispenser.','13512964'),(90,34,'Paper dispensing','Confirm refill format and installation position for a practical washroom routine.','13447594')])]
    panels=''
    for key,num,name,title,art,pid,points in scenes:
        product=pick(pid)
        point_html=''.join(f'<button type="button" class="scene-point" style="--x:{x}%;--y:{y}%" data-point="{i}" aria-pressed="{str(i==0).lower()}" aria-label="Explore {E(label)}"><span>{i+1:02}</span></button>' for i,(x,y,label,desc,point_pid) in enumerate(points))
        details=''.join(f'<template data-point-detail="{i}"><h3>{E(label)}</h3><p>{E(desc)}</p>{image(pick(point_pid).get("image"),pick(point_pid)["title"],cls="scene-product")}<a class="text-link" href="{pick(point_pid)["path"]}">View equipment {arrow}</a><span class="point-product-name">{E(pick(point_pid)["title"])}</span></template>' for i,(x,y,label,desc,point_pid) in enumerate(points))
        first=points[0]
        panels+=f'<section class="scene-panel" id="scene-{key}" aria-label="{name} concept" data-scene-panel="{key}" {"hidden" if key!="hotel" else ""}><div class="scene-visual">{image(visuals[art],name+" concept illustration",cls="scene-photo")}<div class="scene-waves" aria-hidden="true"><i></i><i></i><i></i></div>{point_html}<span class="scene-image-note">Concept illustration · suggested points</span></div><div class="scene-details"><p class="eyebrow">{num} / {name}</p><h3 class="scene-title">{title}</h3><div class="point-details"><h3>{first[2]}</h3><p>{first[3]}</p>{image(product.get("image"),product["title"],cls="scene-product")}<a class="text-link" href="{product["path"]}">View equipment {arrow}</a></div>{details}</div></section>'
    return f'''<section class="spatial-section section" id="space-experience" data-showroom><div class="wrap"><div class="section-head"><div><p class="eyebrow">The spatial showroom</p><h2>Imagine it<br>in <em>your space.</em></h2></div><p class="muted">Choose a setting. Explore the equipment points. Shape a conversation with KWS.</p></div><div class="scene-tabs" aria-label="Choose a setting">{''.join(f'<button type="button" data-scene="{key}" aria-controls="scene-{key}" aria-pressed="{str(key=="hotel").lower()}"><span>{num}</span>{name}</button>' for key,num,name,*rest in scenes)}</div>{panels}<div class="scene-toolbar"><div class="scene-settings"><label for="scene-schedule">Operating preference</label><select id="scene-schedule"><option value="business">Business hours</option><option value="extended">Extended hours</option></select><button type="button" class="btn outline" data-scene-play aria-pressed="false" hidden>Start demonstration {arrow}</button></div><a class="btn" data-scene-inquiry href="/contact/?product=Hotel%20lobby%20concept">Discuss this setting {arrow}</a></div><p class="scene-advice" aria-live="polite">Business-hours preference: discuss a suitable schedule and the selected model’s timer options.</p><p class="fine-print">Illustrative experience only. The animation does not predict scent coverage, concentration or hygiene performance. Confirm the real layout, installation and model-specific settings with KWS.</p><noscript><p class="notice">The hotel concept is shown above. Enable JavaScript to switch settings and explore the equipment points.</p></noscript></div></section>'''
# Home
slides=[(hero,'Make space<br>for <em>better.</em>','Scent diffusion and hygiene essentials, thoughtfully made for the spaces we share.','FRAGRANCE & EVERYDAY SPACES','Discover scent diffusion'),(hygiene,'Care in<br>every <em>detail.</em>','Thoughtful hygiene equipment for the spaces your guests and team use every day.','HYGIENE & EVERYDAY CARE','Discover hygiene essentials'),(pick('13528310'),'Fragrance,<br>made <em>personal.</em>','A 200ml glass-bottle reed diffuser for a considered finishing touch. Explore the product and discuss your fragrance requirements.','REED DIFFUSERS & FRAGRANCE','Discover the 200ml reed diffuser')]
templates=''.join(f'<template data-hero-slide><img class="slide-atmosphere" src="/assets/editorial/{"washroom-scene" if product==hygiene else "planning" if product==hero else "office-scene"}.webp" alt=""><div class="slide-title">{title}</div><p class="slide-copy">{E(copy)}</p><span class="slide-label">KWS HYGIENE / {label}</span>{image(product.get("image"),product["title"],cls="slide-image")}<a class="slide-link" href="{product["path"]}">{caption} {arrow}</a></template>' for product,title,copy,label,caption in slides)
body=f'''<section class="hero carousel cinematic-hero" data-carousel role="region" aria-roledescription="carousel" aria-label="Featured product collections"><img class="hero-atmosphere" id="hero-atmosphere" src="/assets/editorial/planning.webp" width="1536" height="1024" alt="" fetchpriority="high"><div class="hero-shade"></div><div class="wrap hero-grid"><div class="hero-copy"><div class="hero-signature" aria-hidden="true">KWS<span>THE ART OF EVERYDAY SPACES</span></div><div class="hero-wordmark" id="hero-label">KWS HYGIENE / FRAGRANCE & EVERYDAY SPACES</div><h1 id="hero-title">Make space<br>for <em>better.</em></h1><p id="hero-copy">Scent diffusion and hygiene essentials, thoughtfully made for the spaces we share.</p><div class="btn-row"><a href="/products/" class="btn">Explore products {arrow}</a><a href="/about/" class="btn outline">Meet KWS {arrow}</a></div></div><div class="hero-art">{image(hero.get('image'),hero['title'],eager=True).replace('<img ','<img id="hero-image" ',1)}<a class="hero-caption" id="hero-link" href="{hero['path']}">Discover scent diffusion {arrow}</a></div></div><div class="wrap carousel-controls" hidden><button type="button" data-carousel-prev aria-label="Previous slide">←</button><span id="carousel-status" aria-live="off">01 / 03</span><button type="button" data-carousel-next aria-label="Next slide">→</button><div class="carousel-dots">{''.join(f'<button type="button" data-carousel-index="{i}" aria-label="Show slide {i+1}" aria-pressed="{str(i==0).lower()}"></button>' for i in range(3))}</div><button type="button" data-carousel-pause aria-label="Pause carousel">Pause</button></div>{templates}</section><div class="hero-bottom"><span>Fragrance & hygiene equipment</span><span>OEM / ODM inquiries welcome</span><span>Dongguan, China</span></div>
<section class="section wrap reveal"><div class="section-head"><div><p class="eyebrow">Our collections</p><h2>One space.<br>Every essential.</h2></div><p class="muted">From the first impression to everyday care, find the equipment that suits your environment.</p></div><div class="collection-grid"><a class="collection" href="/collections/fragrance/"><div><p class="eyebrow">01 / Fragrance</p><h3>A lasting<br>impression.</h3><p>Diffusers, scent machines<br>and fragrance essentials.</p><span class="text-link">Discover fragrance {arrow}</span></div>{image(hero.get('image'),'KWS commercial scent diffuser',thumb=True)}</a><a class="collection" href="/collections/hygiene/"><div><p class="eyebrow">02 / Hygiene</p><h3>Care in<br>every detail.</h3><p>Dispensers, dryers<br>and washroom essentials.</p><span class="text-link">Discover hygiene {arrow}</span></div>{image(hygiene.get('image'),'KWS touchless soap dispenser',thumb=True)}</a></div></section>
{spatial_showroom()}<section class="section wrap rule reveal"><div class="section-head"><div><p class="eyebrow">Product selection</p><h2>Find your fit.</h2></div><a class="text-link" href="/products/">View all products {arrow}</a></div><div class="product-grid">{''.join(card(p) for p in featured)}</div></section>
<section class="story section"><div class="wrap two-col story-layout"><figure>{image(visuals['workshop-restored'],'AI-restored archival photograph of the KWS assembly workshop',cls='story-image')}<figcaption class="workshop-image-credit">AI-restored archival photograph · <a href="{factory['src']}" target="_blank" rel="noopener">View original {arrow}</a></figcaption></figure><div class="story-copy"><p class="eyebrow">Made by KWS</p><h2>From our workshop<br>to your world.</h2><p>Based in Dongguan, KWS manufactures and supplies fragrance and hygiene equipment, with product development, production and export services.</p><ul class="story-list"><li><span>01</span>Product development & OEM / ODM inquiries</li><li><span>02</span>Production, inspection & shipment preparation</li><li><span>03</span>Installation guidance & after-sales support</li></ul><a class="text-link" href="/manufacturing/">Inside our factory {arrow}</a></div></div></section>
<section class="section wrap reveal"><div class="section-head"><div><p class="eyebrow">Applications</p><h2>Designed around<br>your everyday.</h2></div><a class="text-link" href="/applications/">Explore applications {arrow}</a></div><div class="applications-grid">{app_blocks()}</div></section>'''
if resources['videos']:
    body+=f'<section class="section wrap rule reveal" id="home-videos"><div class="section-head"><div><p class="eyebrow">In motion</p><h2>See the details.</h2></div><a class="text-link" href="/resources/">All product videos {arrow}</a></div><p class="fine-print video-intro">Previews play silently when in view. Open a demonstration for the full video and sound.</p><div class="video-grid">'
    for v in resources['videos'][-3:]:
        body+=f'<article class="video-card preview-card"><div class="video-picture"><video data-hls="{E(v.get("hls",""))}" data-preview muted loop playsinline preload="none" poster="{E(v["poster"]["src"])}" aria-label="Silent preview: {E(v["title"])}"></video><button type="button" class="preview-toggle" aria-label="Pause preview">Pause</button></div><h3><a href="/resources/v-{v["id"]}/">{E(v["title"])}</a></h3><a class="text-link" href="/resources/v-{v["id"]}/">Watch full video {arrow}</a></article>'
    body+='</div></section><script defer src="/assets/vendor/hls.light.min.js"></script><script defer src="/assets/video.js"></script>'
page('/','Fragrance & hygiene equipment','Explore KWS scent diffusers, fragrance essentials and hygiene equipment for hospitality, retail, workplaces and everyday spaces.',body+cta(),schema={'@context':'https://schema.org','@type':'Organization','name':'Dongguan KWS Hygiene Industrial Co., Ltd.','email':'mandyxu@scentairmachines.com','telephone':'+86-13590491364',**({'url':SITE_URL} if SITE_URL else {})})
# Catalog, collection and category pages share one complete accessible catalog.
def catalog(path,title,desc,selected=None,group=None):
    subset=[p for p in products if (not selected or p['category']==selected) and (not group or category_map[p['category']]['group']==group)]
    links=f'<a href="/products/" class="{"active" if not selected and not group else ""}">All products</a>'+''.join(f'<a href="/categories/{c["slug"]}/" class="{"active" if c["source"]==selected else ""}" {"aria-current=page" if c["source"]==selected else ""}>{E(c["name"])}</a>' for c in categories if not group or c['group']==group)
    toolbar='''<div class="catalog-toolbar"><div><label for="product-search">Search products or model</label><input id="product-search" type="search" placeholder="Try HVAC, 500ml or KWS-500" autocomplete="off"></div><div><label for="product-sort">Sort by</label><select id="product-sort"><option value="featured">Original order</option><option value="name">Product name</option><option value="model">Model number</option></select></div></div>'''
    content=intro('Product collections',E(title),E(desc),'Products')+f'<section class="wrap catalog-layout" data-catalog><aside class="category-sidebar"><h2>Categories</h2><nav aria-label="Product categories">{links}</nav></aside><div>{toolbar}<div class="catalog-meta"><span id="catalog-status" aria-live="polite">{len(subset)} products</span><a href="/contact/">Need help choosing? {arrow}</a></div><div class="product-grid catalog-grid" id="catalog-grid">'+''.join(card(p,True) for p in subset)+'''</div><div class="catalog-empty" id="catalog-empty" hidden><h3>No matching products.</h3><p>Try a shorter keyword or browse another category.</p><div class="btn-row" style="justify-content:center"><button class="btn outline" id="clear-search" type="button">Clear search</button><a class="btn" href="/contact/">Ask our team</a></div></div><nav class="pagination" id="pagination" aria-label="Product pages"></nav></div></section>'''
    page(path,title,desc,content,'products')
catalog('/products/','Explore the collection.','Scent diffusion, fragrance and hygiene equipment. Browse by category, search by model, or ask our team for product guidance.')
for c in categories:catalog(f'/categories/{c["slug"]}/',c['name'],f'Browse KWS {c["name"].lower()}. View individual product specifications, images and ordering information.',selected=c['source'])
for g in ['Fragrance','Hygiene']:catalog('/collections/'+g.lower()+'/',g+' essentials.','Explore '+('scent machines, diffusers, essential oils and fragrance gift sets.' if g=='Fragrance' else 'soap and paper dispensers, hand dryers, hair dryers and sanitary bins.'),group=g)
# Every source product has a direct standalone page.
for p in products:
    c=category_map[p['category']];basic=p.get('basic',[]);specs=p.get('specs',[]);shipping=p.get('shipping',[])
    selected=[(k,v) for k,v in specs if k.lower() in ['capacity','coverage','material','power','product size','color','installation']][:5] or [(k,v) for k,v in basic if k!='Certification'][:4]
    quick='<dl class="quick-specs">'+''.join(f'<div><dt>{E(k)}</dt><dd>{E(v)}</dd></div>' for k,v in selected)+'</dl>'
    gallery=p.get('gallery',[])[:12];main=p.get('image');thumbs=''.join(f'<button type="button" data-gallery-src="{E(m["src"])}" data-gallery-alt="{E(p["title"])} — image {i+1}" aria-label="View product image {i+1}" aria-pressed="{str(i==0).lower()}">{image(m,p["title"]+f" image {i+1}",thumb=True)}</button>' for i,m in enumerate(gallery))
    main_img=image(main,p['title'],eager=True).replace('<img ','<img id="gallery-image" ',1)
    gallery_markup=f'<div data-gallery><button type="button" class="gallery-main" id="gallery-zoom" aria-label="Enlarge product image">{main_img}</button><div class="gallery-thumbs">{thumbs}</div><p class="fine-print">Select an image. Click the main image to enlarge.</p></div>' if main else main_img
    query=quote((p.get('model')+' — ' if p.get('model') else '')+p['title'])
    body=f'<div class="wrap product-intro"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><a href="/products/">Products</a><span>/</span><a href="/categories/{c["slug"]}/">{E(c["name"])}</a></nav><div class="product-detail-grid">{gallery_markup}<div class="product-summary"><p class="eyebrow">{E(c["name"])}</p><p class="model">{E(p.get("model") or "KWS "+p["id"])}</p><h1>{E(p["title"])}</h1>{quick}<div class="btn-row"><a class="btn" href="/contact/?product={query}">Request a quote {arrow}</a><a class="btn outline" href="https://wa.me/8613590491364?text={quote("Hello KWS, I would like details about "+p["title"])}" target="_blank" rel="noopener">WhatsApp {arrow}</a></div><p class="fine-print">Please confirm current availability, lead time and product-specific documentation with our team.</p></div></div></div>'
    body+='<div class="wrap"><nav class="detail-nav" aria-label="Product details"><a href="#specifications">Specifications</a><a href="#product-details">Product details</a><a href="#ordering">Ordering information</a></nav>'
    safe_basic=[(k,v) for k,v in basic if k not in dict(specs)];full=safe_basic+specs
    spec_rows=''.join(f'<tr><th scope="row">{E(k)}</th><td>{E(v)}</td></tr>' for k,v in full)
    body+=f'<section class="details-layout" id="specifications"><h2>Specifications</h2><div><table class="spec-table"><tbody>{spec_rows}</tbody></table></div></section>'
    body+=f'<section class="details-layout" id="product-details"><h2>The details.</h2><div class="prose detail-description">{p.get("description_html") or "<p>Contact our team for detailed product information.</p>"}</div></section>'
    body+=f'<section class="details-layout section" id="ordering"><h2>Ordering & support</h2><div><table class="spec-table"><tbody>'+''.join(f'<tr><th scope="row">{E(k)}</th><td>{E(v)}</td></tr>' for k,v in shipping)+'</tbody></table><p class="fine-print" style="margin-top:22px">Ordering terms are product-specific. Request a current quotation before placing an order.</p></div></section></div>'
    related=[x for x in products if x['id']!=p['id'] and x['category']==p['category'] and x.get('image')][:4]
    if related:body+=f'<section class="section wrap rule"><div class="section-head"><div><p class="eyebrow">More to explore</p><h2>Related products.</h2></div></div><div class="product-grid">'+''.join(card(x) for x in related)+'</div></section>'
    schema={'@context':'https://schema.org','@type':'Product','name':p['title'],'brand':{'@type':'Brand','name':'KWS'},'sku':p['id']}
    if p.get('model'):schema['model']=p['model']
    if SITE_URL and main:schema['image']=SITE_URL+main['src']
    page(p['path'],p['title'],p['title']+'. View product specifications and contact KWS for a quotation.',body,'products',schema=schema,zoom=True)
# Application pages: product-guidance routes, never fabricated installation cases.
body=intro('Applications','Find your everyday fit.','Explore product families for hospitality, retail, workplaces and personal spaces. Talk to our team to confirm the right configuration.','Applications')+spatial_showroom()+f'<section class="section wrap"><div class="applications-grid">{app_blocks()}</div><div class="applications-grid">'
for num,name,desc,cat in [('04','Home & personal spaces','Compact aroma and fragrance products for everyday environments.','Aroma Scent Machine'),('05','On the move','Car fragrance products with product-specific power and capacity options.','Car Scent Diffuser'),('06','Gifting & fragrance','Explore essential oils and fragrance gift sets.','Fragrance Gift Sets')]:
    body+=f'<article class="application"><span class="index">{num}</span><h3>{name}</h3><p>{desc}</p><a class="text-link" href="/categories/{category_map[cat]["slug"]}/">Explore products {arrow}</a></article>'
body+='</div></section>'+cta();page('/applications/','Applications','Explore KWS fragrance and hygiene product families for different spaces.',body,'applications')
# Company: consistent entity, source-grounded narrative, no contradictory metrics.
about_source=BeautifulSoup((ROOT/'research/aboutus.html').read_text(),'html.parser')
def clean_source(node):
    if not node:return ''
    from import_content import sanitize
    return sanitize(str(node),media).replace('Shenzhen KWS Hygiene Industrial Co., Ltd.','Dongguan KWS Hygiene Industrial Co., Ltd.')
body=f'<section class="company-hero"><div><p class="eyebrow">About KWS</p><h1>Better spaces.<br>Made together.</h1><p class="lead muted">Dongguan KWS Hygiene Industrial Co., Ltd. manufactures and supplies fragrance and cleaning products from Dongguan, Guangdong.</p></div>{image(factory,"The KWS production team")}</section>'
body+='<section class="section wrap two-col"><div><p class="eyebrow">Who we are</p><h2>Fragrance.<br>Hygiene.<br>Everyday care.</h2></div><div class="prose"><p>Established in Dongguan in 2015, KWS develops and supplies scent machines, aerosol dispensers, soap and sanitizer dispensers, paper dispensers, hair dryers and hand dryers.</p><p>We work with overseas customers on product selection, OEM / ODM requirements, production and after-sales support.</p><p>Our approach brings together product development, manufacturing and export services, with attention to quality, service and practical use.</p><a class="text-link" href="/manufacturing/">Explore our manufacturing '+arrow+'</a></div></section>'
body+='<section class="section wrap rule"><p class="eyebrow">Our journey</p><div class="section-head"><h2>Growing with our customers.</h2></div><div class="timeline">'
for year,title,desc in [('2005–2014','The beginning','The company history traces its roots to Shenzhen Kaili Sanitary Ware Co., Ltd., supplying OEM aerosol dispensers and fragrance products.'),('2015–2016','A home in Dongguan','Dongguan KWS Hygiene Industrial Co., Ltd. was established in Tangxia, with a focus on fragrance equipment.'),('2017','Project cooperation','The source history records fragrance project cooperation with OPPEIN and EIFINI.'),('2018–2020','International partnerships','The company history records overseas distribution and agency cooperation.')]:
    body+=f'<article><p class="year">{year}</p><h3>{title}</h3><p>{desc}</p></article>'
body+='</div></section><section class="section wrap rule"><div class="section-head"><div><p class="eyebrow">Working with you</p><h2>Support, beyond the product.</h2></div><p class="muted">From the first project brief to everyday operation, explore how KWS supports your team.</p></div>'
services=[('Technical training','Guidance for the people who use your equipment.','Installation, commissioning, operation and maintenance are part of the training described by KWS. Discuss the instructions and training your technicians or operators need for the selected product.','training'),('Inspection & after-sales support','A clear route from a question to the next step.','The KWS service information describes pre-shipment inspection, customer feedback and technical assistance. Confirm warranty coverage, repair arrangements and any paid service terms for your order.','quality'),('Fragrance project planning','Start with the space and the business requirement.','The service process begins with consultation and a review of the environment. Share your operating requirements, airflow and the way people use the space before discussing a fragrance proposal.','planning'),('A considered service process','From a brief to an agreed installation.','Consultation, facility review, fragrance selection, installation and ongoing support form the service process described by KWS. Confirm the scope and any customization with your quotation.','service-process'),('Fragrance & odor-control inquiries','Discuss the intended result before choosing a refill.','Tell the team about the environment, the fragrance preference and the issue you want to address. Ask for product-specific compatibility, instructions and a sample where appropriate; fragrance equipment does not replace cleaning or ventilation.','fragrance-selection')]
for i,(title,headline,copy,art) in enumerate(services):
    body+=f'<article class="service-row"><div class="service-copy"><p class="eyebrow">0{i+1} / {title}</p><h3>{headline}</h3><p>{copy}</p><a class="text-link" href="/contact/">Discuss your requirements {arrow}</a></div><figure>{image(visuals[art],title+" conceptual illustration")}<figcaption>Service concept illustration</figcaption></figure></article>'
body+='</section>'
team_captions=['Office & product display','Team collaboration','Reception & showroom','Machining workspace','Production equipment','Workshop environment']
body+='<section class="section wrap rule"><div class="section-head"><div><p class="eyebrow">Our people & workplace</p><h2>The team behind KWS.</h2></div><p class="fine-print">Original KWS workplace photographs. Select an image to view the original detail.</p></div><div class="workplace-grid">'
for i,title in enumerate(team_captions):
    m=visuals[f'workplace-{i+1}'];body+=f'<figure><button class="workplace-zoom" type="button" data-zoom-src="{m["src"]}" data-zoom-alt="{title}" aria-label="Enlarge {title}">{image(m,title)}</button><figcaption>{title} <span aria-hidden="true">↗</span></figcaption></figure>'
body+='</div></section>'+cta()
page('/about/','About KWS','Meet Dongguan KWS Hygiene Industrial Co., Ltd., our history, services and team.',body,'about',zoom=True)
# Manufacturing
def factory_photo(m, caption, eager=False):
    restoration={'/assets/media/a982014155b23d9f1abe.webp':'workshop-restored','/assets/media/c39c113bf5fb7132f024.webp':'machining-restored','/assets/media/1631c47b465022cb0211.webp':'molding-restored','/assets/media/4de39fda638167c912ee.webp':'storage-restored'}
    derivative=visuals[restoration[m['src']]]
    return f'<figure class="restored-factory-photo">{image(derivative,"AI-restored archival photograph: "+caption,eager=eager)}<figcaption>{E(caption)}<span class="factory-restoration-note">AI-restored archival photograph · <a href="{m["src"]}" target="_blank" rel="noopener">View original {arrow}</a></span></figcaption></figure>'
factory_source=BeautifulSoup((ROOT/'research/factory.html').read_text(),'html.parser');factory_images=[asset(i.get('data-original') or i.get('src')) for i in factory_source.select('.left-content img')]
body=intro('Manufacturing','From idea<br>to everyday use.','Product development, manufacturing and export support for fragrance and hygiene equipment. Explore the workshop and plan your next project with KWS.','Manufacturing')
body+=f'<section class="wrap manufacturing-lead"><div>{factory_photo(factory,"KWS assembly workshop",eager=True)}</div><div class="manufacturing-copy"><p class="eyebrow">Made in Dongguan</p><h2>A practical path<br>to your product.</h2><p>KWS brings product selection, OEM / ODM inquiries, production and shipment preparation into one conversation. Start with your application and confirm the details that matter to your order.</p><div class="btn-row"><a class="btn" href="/contact/">Start a manufacturing inquiry {arrow}</a><a class="text-link" href="/quality/">Quality & documents {arrow}</a></div></div></section>'
body+='<section class="section wrap"><div class="section-head"><div><p class="eyebrow">Production environment</p><h2>Inside the workshop.</h2></div><p class="muted">Restored archival KWS photographs show assembly, machining, molding equipment and the production environment. Original photographs remain available for comparison.</p></div><div class="factory-grid">'+''.join(factory_photo(m,["Assembly and product preparation","Machining workshop","Injection molding equipment","Product storage and production area"][i%4]) for i,m in enumerate(factory_images) if m)+'</div></section>'
body+='<section class="manufacturing-process"><div class="wrap section"><div class="section-head"><div><p class="eyebrow">A clear production process</p><h2>Attention at every stage.</h2></div><p>The source factory description identifies a 5S workshop management approach, from material purchasing to manufacture, testing and packing.</p></div><div class="production-stages">'
for i,(title,desc) in enumerate([('Define the requirement','Confirm application, product model, quantity and the intended installation. A clear brief helps the team identify the right starting point.'),('Review samples & options','Discuss samples, OEM / ODM requests and packaging options. Agree the approved specification and any artwork before ordering.'),('Materials & manufacture','Material purchasing and manufacturing follow the confirmed product requirements. Confirm any model-specific requirements with the team.'),('Inspect & test','The factory information describes product testing before shipment. Ask which inspection and documentation apply to your selected model.'),('Pack & prepare','Confirm protective packaging, quantities and shipment terms in the quotation. Keep the approved product and packaging references together.'),('Support everyday use','Retain operating instructions and the product identifier. Agree the training, warranty and support arrangements for your order.')]):
    body+=f'<article><span class="stage-number">0{i+1}</span><h3>{title}</h3><p>{desc}</p></article>'
body+='</div></div></section>'
body+=f'<section class="section wrap service-row"><div class="service-copy"><p class="eyebrow">OEM / ODM collaboration</p><h2>Your brief.<br>Our conversation.</h2><p>Share the application, target quantity, product references and requested changes. The team can discuss available customization, samples and the approval process for the selected model.</p><ul class="manufacturing-checklist"><li>Application and model references</li><li>Branding, finish and packaging requirements</li><li>Samples, approvals and order documentation</li><li>Quantity, lead time and shipment terms</li></ul><a class="text-link" href="/news/oem-odm-project-brief/">Read the OEM / ODM checklist {arrow}</a></div><figure>{image(visuals["training"],"Conceptual illustration of a technical product review")}<figcaption>Product collaboration concept illustration</figcaption></figure></section>'
body+=f'<section class="section wrap rule service-row"><figure>{image(visuals["quality"],"Conceptual illustration of an equipment inspection")}<figcaption>Quality process concept illustration</figcaption></figure><div class="service-copy"><p class="eyebrow">Quality & documentation</p><h2>Ask the right<br>quality questions.</h2><p>Inspection, testing and packaging are described in the original KWS factory information. Documents are product-specific: confirm the applicable model, full report and current status for your order.</p><a class="btn" href="/quality/">Explore quality & documents {arrow}</a></div></section>'+cta()
page('/manufacturing/','Manufacturing','Explore KWS production facilities, OEM / ODM collaboration, workshop management and shipment preparation.',body,'manufacturing')
# Deduplicate source certificates by standard / number / issued date while retaining all scans for duplicates.
q=BeautifulSoup((ROOT/'research/quality.html').read_text(),'html.parser');certificates={}
for li in q.select('#certificatestitle .card-item'):
    fields={}
    for x in li.select('.text-item'):
        k,_,v=x.get_text(' ',strip=True).partition(':');fields[k.strip()]=v.strip()
    if fields.get('Standard')=='TEST ROPORT':fields['Standard']='TEST REPORT'
    key=(fields.get('Standard'),fields.get('Number'),fields.get('Issue Date'));im=li.select_one('img');scan=asset(im.get('src')) if im else None
    item=certificates.setdefault(key,{**fields,'scans':[]})
    if scan:item['scans'].append(scan)
certs=list(certificates.values());(CONTENT/'certificates.json').write_text(json.dumps(certs,indent=2))
body=intro('Quality & documents','Care, at every step.','From materials and inspection to packaging and service, explore the KWS quality process and available product documents.','Quality')
body+=f'<section class="wrap quality-process"><div class="quality-overview"><p class="eyebrow">From preparation to support</p><h2>Quality through<br>the process.</h2><p class="quality-summary">Explore product preparation, shipment and ongoing support. Discuss the requirements for your selected model with KWS.</p><figure><img src="/assets/editorial/workshop-restored-v1.webp" width="1536" height="1024" alt="KWS assembly workshop" loading="lazy"><figcaption>Assembly at KWS · AI-restored archival photograph</figcaption></figure><div class="quality-actions"><a class="text-link" href="/manufacturing/">Explore manufacturing {arrow}</a><a class="text-link" href="#document-library">View product documents {arrow}</a></div></div><ol class="process-list">' 
for title,desc in [('Material sourcing','Selection of raw materials from suppliers. Discuss materials, finishes and requirements for your selected model.'),('Quality inspection','Inspection of equipment during production. Ask which inspection items apply to your equipment and configuration.'),('Pre-shipment testing','Product testing before shipment. Confirm the applicable functional checks and available documents with our team.'),('Protective packaging','Packaging selected to protect products in transit. Discuss packing requirements and shipment arrangements for your order.'),('After-sales support','Technical assistance and follow-up for product questions. Share the model and issue for operation or maintenance guidance.')]:body+=f'<li><div><h3>{title}</h3><p>{desc}</p></div></li>'
body+='</ol></section><section class="section wrap" id="document-library"><div class="section-head"><div><p class="eyebrow">Document library</p><h2>Certificates & reports.</h2></div></div><p class="fine-print" style="margin-bottom:32px">Documents are product-specific. Ask our team to confirm the applicable model, full report and current document status for your order.</p><div class="certificate-grid">'
for c in certs:
    im=c['scans'][0] if c['scans'] else None
    if not im:continue
    scanlinks=''.join(f'<button type="button" class="text-link" data-zoom-src="{E(scan["src"])}" data-zoom-alt="{E(c.get("Number",""))}" style="background:transparent;width:auto;height:auto;padding:8px 0">View scan {i+1} {arrow}</button>' for i,scan in enumerate(c['scans']))
    body+=f'<article class="certificate"><button type="button" data-zoom-src="{E(im["src"])}" data-zoom-alt="{E(c.get("Number",""))}" aria-label="Enlarge {E(c.get("Standard",""))} document {E(c.get("Number",""))}">{image(im,c.get("Number","") ,thumb=True)}</button><h3>{E(c.get("Standard","Document"))}</h3><p>{E(c.get("Number",""))}<br>Issued {E(c.get("Issue Date",""))}</p>{scanlinks if len(c['scans'])>1 else ""}</article>'
body+='</div></section>'+cta();page('/quality/','Quality & documents','Explore the KWS quality process, certificates and test reports. Confirm product-specific documentation with our team.',body,'manufacturing',zoom=True)
# Video resources: migrated local video where available, honest external source fallback otherwise.
body=intro('Resources','A closer look.','Explore product demonstrations and the details that help you choose.','Resources')+'<section class="wrap section" style="padding-top:0"><div class="video-grid">'
for v in resources['videos']:
    body+=f'<a class="video-card" href="/resources/v-{v["id"]}/"><div class="video-picture">{image(v.get("poster"),v["title"],thumb=True)}<span class="play-mark" aria-hidden="true">▶</span></div><h3>{E(v["title"])}</h3></a>'
body+='</div></section>'+cta();page('/resources/','Product videos','Watch KWS fragrance and hygiene product demonstrations.',body,'resources')
for v in resources['videos']:
    poster_attr=f'poster="{E(v["poster"]["src"])}"' if v.get("poster") else ""
    hls_player=f'<script defer src="/assets/vendor/hls.light.min.js"></script><script defer src="/assets/video.js"></script><video controls playsinline preload="none" class="resource-video" data-hls="{E(v.get("hls",""))}" {poster_attr} aria-label="{E(v["title"])}"></video><p id="video-error" class="fine-print" hidden>Video playback is unavailable in this browser. <a href="{E(v["source"])}" target="_blank" rel="noopener">Watch on the original KWS website</a>.</p>' if v.get("hls") else ""
    video=f'<video controls playsinline preload="metadata" class="resource-video" {poster_attr}><source src="{E(v["video"])}" type="video/mp4"><p>Your browser does not support this video. <a href="{E(v["video"])}">Open video</a>.</p></video>' if v.get('video') else f'<div class="notice"><p>This video is available on the original KWS website.</p><div class="btn-row"><a href="{E(v["source"])}" target="_blank" rel="noopener" class="btn">Watch the original video {arrow}</a></div></div>'
    if hls_player:video=hls_player
    page(f'/resources/v-{v["id"]}/',v['title'],v['title']+' — KWS product demonstration.',intro('Product demonstration',E(v['title']),'','Product videos')+f'<section class="wrap">{video}<div class="resource-meta"><p>{E(v.get("text", ""))}</p><div class="btn-row"><a class="text-link" href="/resources/">All videos {arrow}</a><a class="btn" href="/contact/?product={quote(v["title"])}">Ask about this product {arrow}</a></div></div></section>'+cta(),'resources')
# Existing news and business partners content.
news_image=next((asset(i.get('data-original') or i.get('src')) for i in BeautifulSoup((ROOT/'research/news.html').read_text(),'html.parser').select('img') if '/photo/' in (i.get('data-original') or i.get('src',''))),None)
def editorial_image(article):
    key=article['image']
    return visuals[key] if key in visuals else pick({'hygiene':'13512964','paper':'13447594','oil':'13490105'}[key]).get('image')
body=intro('News & insights','Ideas for<br>better spaces.','Company updates and practical guides to fragrance, hygiene equipment, manufacturing and everyday use.','News')+'<section class="wrap section" style="padding-top:0"><div class="news-grid">'
for article in editorial:
    body+=f'<article class="news-card"><a class="news-card-image" href="/news/{article["slug"]}/">{image(editorial_image(article),article["title"])}</a><div class="news-card-body"><p class="eyebrow">{E(article["tag"])}</p><h2><a href="/news/{article["slug"]}/">{E(article["title"])}</a></h2><p class="muted">{E(article["summary"])}</p><div class="news-card-meta"><span>06 October 2026 · Editorial guide</span><a href="/news/{article["slug"]}/" aria-label="Read {E(article["title"])}">Read {arrow}</a></div></div></article>'
body+=f'<article class="news-card"><a class="news-card-image" href="/news/team-building/">{image(news_image,"KWS team building activity")}</a><div class="news-card-body"><p class="eyebrow">Company archive</p><h2><a href="/news/team-building/">Our team, outside the workshop.</a></h2><p class="muted">A team-building update from the original KWS company website.</p><div class="news-card-meta"><span>21 February 2021</span><a href="/news/team-building/">Read {arrow}</a></div></div></article></div></section>'+cta()
page('/news/','News & insights','KWS company updates and practical fragrance, hygiene and manufacturing guides.',body,'resources')
for article in editorial:
    content=intro(article['tag'],E(article['title']),E(article['summary']),'News & insights')
    content+=f'<section class="wrap article-cover">{image(editorial_image(article),article["title"],eager=True)}<p class="fine-print">06 October 2026 · KWS editorial guide'+(' · Concept illustration' if article['image'] in visuals else '')+'</p></section><div class="wrap article-layout"><article class="prose article-prose">'
    for section in article['sections']:content+=f'<section><h2>{E(section["title"])}</h2><p>{E(section["text"])}</p></section>'
    content+=f'<section class="article-checklist"><h2>Your inquiry checklist</h2><ul>'+''.join(f'<li>{E(item)}</li>' for item in article['checklist'])+'</ul></section><p class="fine-print">Product selection guidance. Confirm specifications, compatibility, installation and commercial terms for the exact model with KWS.</p></article>'
    content+=f'<aside class="article-sidebar"><p class="eyebrow">Explore the range</p><h2>Find the right<br>starting point.</h2><p>Browse related products and send your project requirements to the team.</p><a class="btn" href="/categories/{article["category"]}/">Related products {arrow}</a><a class="text-link" href="/contact/">Talk to KWS {arrow}</a><a class="text-link" href="/news/">All news & insights {arrow}</a></aside></div>'+cta()
    page('/news/'+article['slug']+'/',article['title'],article['summary'],content,'resources')
newsbody=resources['news'][0].get('html','') if resources['news'] else ''
if not newsbody:
    n=next(iter((ROOT/'research/details').glob('*team-building*')),None)
    if n:
        bs=BeautifulSoup(n.read_text(),'html.parser');node=bs.select_one('.news-body') or bs.select_one('.news-content');newsbody=clean_source(node)
page('/news/team-building/','KWS team building','KWS team-building update, originally published 21 February 2021.',intro('21 February 2021','A day together.','Team building at KWS.','Company news')+'<section class="wrap legal prose">'+(newsbody or image(news_image,'KWS team building activity'))+'</section>','resources')
partners=BeautifulSoup((ROOT/'research/cases__our-business-partners-1898.html').read_text(),'html.parser');partnerimgs=[asset(i.get('data-original') or i.get('src')) for i in partners.select('img') if '/photo/' in (i.get('data-original') or i.get('src',''))]
page('/about/partners/','Business partners','Business partner materials from the original KWS website.',intro('24 February 2021','Business partners.','Partner materials shared on the original KWS website. Contact our team for current project references.','About KWS')+'<section class="wrap legal prose">'+''.join(image(m,'KWS business partner materials') for m in partnerimgs if m)+'</section>','about')
# Contact: no fake send action; draft review precedes real channel launch.
form='''<form id="inquiry-form" class="inquiry-form"><p class="eyebrow">Tell us what you need</p><h2 style="font-size:32px;margin-bottom:28px">Let's find the right fit.</h2><div class="form-grid"><div class="field"><label for="inquiry-name">Your name *</label><input id="inquiry-name" name="name" required maxlength="100" autocomplete="name"></div><div class="field"><label for="inquiry-email">Email address *</label><input id="inquiry-email" name="email" type="email" required maxlength="180" autocomplete="email"></div><div class="field"><label for="inquiry-company">Company</label><input id="inquiry-company" name="company" maxlength="180" autocomplete="organization"></div><div class="field"><label for="inquiry-country">Country / region</label><input id="inquiry-country" name="country" maxlength="100" autocomplete="country-name"></div></div><div class="field"><label for="inquiry-product">Product / model</label><input id="inquiry-product" name="product" maxlength="400"></div><div class="field"><label for="inquiry-quantity">Quantity</label><input id="inquiry-quantity" name="quantity" maxlength="100" placeholder="For example: 100 units"></div><div class="field"><label for="inquiry-message">Your requirements *</label><textarea id="inquiry-message" name="message" required minlength="20" maxlength="3000" rows="5" placeholder="Tell us about your application and product requirements." aria-describedby="message-help"></textarea><small id="message-help">20–3,000 characters.</small></div><button class="btn" type="submit">Prepare inquiry <span class="arrow" aria-hidden="true">↗</span></button><p class="fine-print" style="margin-top:16px">Review your inquiry, then send it using your email app or WhatsApp. Preparing a draft does not send a message.</p><noscript><p>Please contact us directly by email or WhatsApp to make an inquiry.</p></noscript><div id="draft-preview" class="draft-preview" hidden><h3 id="draft-heading" tabindex="-1">Your inquiry is ready to review.</h3><label class="visually-hidden" for="draft-text">Inquiry draft</label><textarea id="draft-text" readonly></textarea><div class="btn-row"><a id="draft-email" class="btn">Open email draft ↗</a><a id="draft-whatsapp" class="btn outline" target="_blank" rel="noopener">Open WhatsApp draft ↗</a><button id="copy-draft" type="button" class="text-link" style="background:transparent">Copy draft</button></div><p class="fine-print" style="margin-top:16px">No message has been sent from this website. Send the draft in your email app or WhatsApp to complete your inquiry.</p><p class="copy-feedback" id="copy-feedback" aria-live="polite"></p></div></form>'''
body=intro('Contact KWS','Good spaces start<br>with a conversation.','Product questions, samples, OEM / ODM requirements or distribution inquiries — talk to Mandy and the KWS team.','Contact')+f'<section class="wrap contact-layout"><div><div class="contact-detail"><p class="eyebrow">Your contact</p><p>Mandy Xu</p><span class="muted">Sales Manager</span></div><div class="contact-detail"><p class="eyebrow">Email</p><p><a href="mailto:mandyxu@scentairmachines.com">mandyxu@scentairmachines.com</a></p></div><div class="contact-detail"><p class="eyebrow">Phone / WhatsApp</p><p><a href="tel:+8613590491364">+86 135 9049 1364</a></p><a class="text-link" href="https://wa.me/8613590491364" target="_blank" rel="noopener">Start on WhatsApp {arrow}</a></div><div class="contact-detail"><p class="eyebrow">Visit us</p><p>Building B, No. 106 Lingnan Road,<br>Tangxia, Dongguan,<br>Guangdong, China</p><p class="fine-print" style="margin-top:12px">Office hours: 08:30–20:30, Beijing time<br>WeChat / Skype: 0086-135-9049-1364<br>Fax: +86 400 811 5229</p></div></div>{form}</section>'
page('/contact/','Contact KWS','Contact Mandy Xu at KWS for products, quotations, OEM / ODM and distribution inquiries.',body)
# Privacy describes the actual static preview behavior; no inherited platform policy.
body=intro('Website privacy','Your inquiry.<br>Your choice.','How this website handles inquiry drafts and external contact links.','Privacy')+'''<section class="wrap legal prose"><h2>Inquiry drafts</h2><p>The inquiry form prepares a draft in your browser. It does not submit your details to a website database or send a message automatically. The draft is not stored in local storage by this website.</p><h2>Email and WhatsApp</h2><p>Choosing an email or WhatsApp link opens the selected service with your draft. Review it before sending. Your email provider or WhatsApp handles the message under its own privacy terms.</p><h2>Images, videos and browsing</h2><p>Product images and migrated videos are served with this website. This version does not include marketing analytics or advertising trackers. The hosting provider may retain ordinary access logs.</p><h2>Contact</h2><p>For questions about an inquiry you have sent, contact <a href="mailto:mandyxu@scentairmachines.com">mandyxu@scentairmachines.com</a>.</p></section>'''
page('/privacy/','Website privacy','How KWS inquiry drafts and contact links work.',body)
body=intro('Site map','Find your way.','Explore every product family and website section.','Site map')+'<section class="wrap section" style="padding-top:0"><div class="two-col"><div><h2 style="font-size:30px">Website</h2><ul>'+''.join(f'<li><a href="{p}">{n}</a></li>' for n,p,k in navitems)+ '<li><a href="/quality/">Quality & documents</a></li><li><a href="/news/">News</a></li><li><a href="/about/partners/">Business partners</a></li><li><a href="/contact/">Contact</a></li><li><a href="/privacy/">Privacy</a></li></ul></div><div><h2 style="font-size:30px">Product categories</h2><ul>'+''.join(f'<li><a href="/categories/{c["slug"]}/">{E(c["name"])}</a></li>' for c in categories)+'</ul></div></div></section>'
page('/site-map/','Site map','Explore KWS website pages and product categories.',body)
page('/404.html','Page not found','Find KWS products and company information.',intro('404','A different direction.','This page is unavailable. Browse our products or contact the KWS team.')+'<section class="wrap section" style="padding-top:0"><div class="btn-row"><a class="btn" href="/">Home '+arrow+'</a><a class="btn outline" href="/products/">Browse products '+arrow+'</a></div></section>')
# Preserve source URL access using generated redirects; production host can replace these with HTTP 301 rules.
def redirect(old,new):
    old=urlparse(old).path
    if not old or old=='/' or old==new:return
    target=OUT/old.lstrip('/');target.parent.mkdir(parents=True,exist_ok=True)
    target.write_text(f'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="robots" content="noindex"><meta http-equiv="refresh" content="0;url={E(new)}"><title>Page moved | KWS</title><p>This page has moved. <a href="{E(new)}">Continue to KWS</a>.</p></html>');redirects.append((old,new))
for p in products:redirect(p['url'],p['path'])
for old,new in [('products.html','/products/'),('aboutus.html','/about/'),('factory.html','/manufacturing/'),('quality.html','/quality/'),('contactus.html','/contact/'),('contactnow.html','/contact/'),('video.html','/resources/'),('video-all.html','/resources/'),('video-playlist.html','/resources/'),('news.html','/news/'),('sitemap.html','/site-map/'),('privacy.html','/privacy/'),('cases/our-business-partners-1898.html','/about/partners/')]:redirect('/'+old,new)
for f in (ROOT/'research').glob('supplier-*.html'):
    b=BeautifulSoup(f.read_text(),'html.parser');name=b.h1.get_text(' ',strip=True) if b.h1 else ''
    if name in category_map:redirect('/'+f.stem,'/categories/'+category_map[name]['slug']+'/')
for v in resources['videos']:redirect(v['source'],f'/resources/v-{v["id"]}/')
for n in resources['news']:redirect(n['source'],'/news/team-building/')
with (CONTENT/'url-map.csv').open('w',newline='') as f:
    w=csv.writer(f);w.writerow(['old_path','new_path']);w.writerows(redirects)
(OUT/'_redirects').write_text('\n'.join(f'{old} {new} 301' for old,new in redirects)+'\n')
(OUT/'_headers').write_text('/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  Content-Security-Policy: default-src \'self\'; script-src \'self\'; style-src \'self\' \'unsafe-inline\'; img-src \'self\' data:; media-src \'self\' blob:; object-src \'none\'; base-uri \'self\'; frame-ancestors \'none\'\n')
(OUT/'robots.txt').write_text('User-agent: *\n'+('Allow: /\nSitemap: '+SITE_URL+'/sitemap.xml\n' if SITE_URL else 'Disallow: /\n'))
if SITE_URL:
    (OUT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+E(SITE_URL+p)+'</loc></url>' for p in routes if p!='/404.html')+'</urlset>')
else:(OUT/'sitemap.xml').unlink(missing_ok=True)
(CONTENT/'build-report.json').write_text(json.dumps({'pages':len(routes),'product_pages':len(products),'categories':len(categories),'certificates':len(certs),'certificate_scans':sum(len(c['scans']) for c in certs),'redirects':len(redirects),'production_url':SITE_URL or None,'routes':routes},indent=2))
print(f'Built {len(routes)} pages, {len(products)} products, {len(certs)} deduplicated document records, {len(redirects)} URL mappings.')
